x-pegasus:
  apiLang: python
  createdBy: bianyiyang
  createdOn: 06-09-22T13:44:10Z
pegasus: '5.0'
name: peakfinding-workflow
transformationCatalog:
  transformations:
  - name: generate_source
    sites:
    - name: local
      pfn: /Users/bianyiyang/airflow/dags/CRUX/workflow_pegasus/generate_source.py
      type: stageable
jobs:
- type: job
  name: generate_source
  id: ID0000001
  arguments: []
  uses: []
jobDependencies: []
